"""add_calorie_tracking_to_meal_compliance

Revision ID: bdcc78b9da0a
Revises: bceed953158f
Create Date: 2026-03-18 16:21:31.165377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdcc78b9da0a'
down_revision: Union[str, Sequence[str], None] = 'bceed953158f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meal_compliance', sa.Column('calories_consumed', sa.Float(), nullable=True))
    op.add_column('meal_compliance', sa.Column('calories_target', sa.Float(), nullable=True))
    op.add_column('meal_compliance', sa.Column('calorie_balance', sa.Float(), nullable=True))
    op.add_column('meal_compliance', sa.Column('weekly_bank_balance', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meal_compliance', 'weekly_bank_balance')
    op.drop_column('meal_compliance', 'calorie_balance')
    op.drop_column('meal_compliance', 'calories_target')
    op.drop_column('meal_compliance', 'calories_consumed')
    # ### end Alembic commands ###
