"""create_sleep_logs_table

Revision ID: 0e72fdcc69af
Revises: aa4ca4f0c8c4
Create Date: 2026-03-13 16:21:05.147292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e72fdcc69af'
down_revision: Union[str, Sequence[str], None] = 'aa4ca4f0c8c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sleep_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('sleep_time', sa.Time(), nullable=True),
    sa.Column('wake_time', sa.Time(), nullable=True),
    sa.Column('duration_hours', sa.Float(), nullable=True),
    sa.Column('quality_score', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sleep_logs_user_id'), 'sleep_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sleep_logs_user_id'), table_name='sleep_logs')
    op.drop_table('sleep_logs')
    # ### end Alembic commands ###
