"""add_user_pref_new_fields

Revision ID: 5d79c5ec0994
Revises: e6c55c10c52b
Create Date: 2026-06-07 03:42:38.191162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d79c5ec0994'
down_revision: Union[str, Sequence[str], None] = 'e6c55c10c52b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing = [col['name'] for col in inspector.get_columns('user_preferences')]

    if 'diet_preference' not in existing:
        op.add_column('user_preferences', sa.Column('diet_preference', sa.String(), nullable=True))
    if 'ai_name' not in existing:
        op.add_column('user_preferences', sa.Column('ai_name', sa.String(length=100), nullable=True))
    if 'target_weight_kg' not in existing:
        op.add_column('user_preferences', sa.Column('target_weight_kg', sa.Float(), nullable=True))
    if 'daily_calorie_habit' not in existing:
        op.add_column('user_preferences', sa.Column('daily_calorie_habit', sa.String(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_preferences', 'daily_calorie_habit')
    op.drop_column('user_preferences', 'target_weight_kg')
    op.drop_column('user_preferences', 'ai_name')
    op.drop_column('user_preferences', 'diet_preference')
    # ### end Alembic commands ###
