"""create_onboarding_profile_table

Revision ID: 6ed107fbbf13
Revises: bdcc78b9da0a
Create Date: 2026-04-05 14:49:22.813322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ed107fbbf13'
down_revision: Union[str, Sequence[str], None] = 'bdcc78b9da0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onboarding_profile',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('goals', sa.JSON(), nullable=True),
    sa.Column('diet_preference', sa.String(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_onboarding_profile_user_id')
    )
    op.create_index(op.f('ix_onboarding_profile_user_id'), 'onboarding_profile', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_onboarding_profile_user_id'), table_name='onboarding_profile')
    op.drop_table('onboarding_profile')
    # ### end Alembic commands ###
