"""add menstrual_cycles table

Revision ID: 873bb037ab61
Revises: c39818c0c220
Create Date: 2026-04-06 17:39:44.657221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '873bb037ab61'
down_revision: Union[str, Sequence[str], None] = 'c39818c0c220'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menstrual_cycles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('cycle_start_date', sa.Date(), nullable=False),
    sa.Column('cycle_length_days', sa.Integer(), nullable=False),
    sa.Column('period_length_days', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('menstrual_cycles')
    # ### end Alembic commands ###
