"""add_target_weight_calorie_habit_burned

Revision ID: e6c55c10c52b
Revises: a1b2c3d4e5f6
Create Date: 2026-06-07 03:35:02.811518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6c55c10c52b'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('onboarding_profile', sa.Column('target_weight_kg', sa.Float(), nullable=True))
    op.add_column('onboarding_profile', sa.Column('daily_calorie_habit', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('onboarding_profile', 'daily_calorie_habit')
    op.drop_column('onboarding_profile', 'target_weight_kg')
    # ### end Alembic commands ###
